server:
  port: 8082
spring:
  application:
    name: test-mail
  mail:
    host: smtp.qq.com             #smtp服务器
    username: 1797147349@qq.com   #发送者邮箱
    password: jehzlmqpdopehejb    #授权码
    port: 587       #端口
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory  #ssl工厂
        debug: true                 #开启控制台调试显示
    default-encoding: utf-8



